/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    id: 1,
    img: "",
    title: "infosys",
    email: "management@infosys.com",
    phone: "+91 9563214587",
    person: "Vijay roy",
    facilitator: "-",
    site: "12",
    tenants: "--",
    tenantGroup: "--",
  },
  {
    id: 2,
    img: "",
    title: "wipro",
    email: "management@wipro.com",
    phone: "+91 9563214587",
    person: "kaplit soni",
    facilitator: "-",
    site: "8",
    tenants: "--",
    tenantGroup: "--",
  },
  {
    id: 3,
    img: "",
    title: "accenture",
    email: "management@accenture.com",
    phone: "+91 9563214587",
    person: "ajay roy",
    facilitator: "-",
    site: "8",
    tenants: "1",
    tenantGroup: "2",
  },
  {
    id: 4,
    img: "",
    title: "capgemini",
    email: "management@capgemini.com",
    phone: "+91 9563214587",
    person: "vamsi varma ",
    facilitator: "-",
    site: "19",
    tenants: "--",
    tenantGroup: "--",
  },
  {
    id: 5,
    img: "",
    title: "lodha",
    email: "management@lodha.com",
    phone: "+91 9563214587",
    person: "aisha varma ",
    facilitator: "-",
    site: "20",
    tenants: "--",
    tenantGroup: "--",
  },
  {
    id: 6,
    img: "",
    title: "infosys",
    email: "management@infosys.com",
    phone: "+91 9563214587",
    person: "Vijay roy",
    facilitator: "-",
    site: "12",
    tenants: "--",
    tenantGroup: "--",
  },
  {
    id: 7,
    img: "",
    title: "wipro",
    email: "management@wipro.com",
    phone: "+91 9563214587",
    person: "kaplit soni",
    facilitator: "-",
    site: "8",
    tenants: "--",
    tenantGroup: "--",
  },
  {
    id: 8,
    img: "",
    title: "accenture",
    email: "management@accenture.com",
    phone: "+91 9563214587",
    person: "ajay roy",
    facilitator: "-",
    site: "8",
    tenants: "1",
    tenantGroup: "2",
  },
  {
    id: 9,
    img: "",
    title: "capgemini",
    email: "management@capgemini.com",
    phone: "+91 9563214587",
    person: "vamsi varma ",
    facilitator: "-",
    site: "19",
    tenants: "--",
    tenantGroup: "--",
  },
  {
    id: 10,
    img: "",
    title: "lodha",
    email: "management@lodha.com",
    phone: "+91 9563214587",
    person: "aisha varma ",
    facilitator: "-",
    site: "20",
    tenants: "--",
    tenantGroup: "--",
  },
];
